error.handling.http-status-in-json-response=true
error.handling.exception-logging=NO_LOGGING
error.handling.full-stacktrace-http-statuses=5xx
error.handling.log-levels.5xx=ERROR
springdoc.pathsToMatch=/

freshservice.base-url=${FRESHSERVICE_BASE_URL:https://eworks-ke.freshservice.com}
freshservice.api-key=${FRESHSERVICE_API_KEY:fwapi_1RRg44Nkxi5DMtJgJUeBeH_1018827041998347332_df59609}
freshservice.agent-id=${FRESHSERVICE_AGENT_ID:3}
